import Head from "next/head";
import Image from "next/image";
import { Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <div 
    // style={{ backgroundColor: "black",
    //  height:'100%' }}
    >
      <Head>
        <title>Marisa Coppa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Marisa Coppa</Heading>
    </div>
  );
}
